import type { Metadata } from "next";
import { Raleway } from "next/font/google";
import "./globals.css";
import Sidebar from "@/components/Sidebar";
import Container from "@/components/Container";
import ModalProvider from "@/provider/ModalProvider";
const inter = Raleway({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="bg-white text-black">
      <body className={inter.className}>
        <Sidebar />
        <Container>{children}</Container>
        <ModalProvider />
      </body>
    </html>
  );
}
